#!/usr/bin/env bash
# script that configure nginx

apt-get update -y && apt-get install nginx -y

service nginx start

ufw allow 'Nginx HTTP'

chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp


echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html


service nginx restart
