#!/usr/bin/env bash
# script that configure nginx

sudo apt-get update -y -qq && sudo apt-get install nginx -y

service nginx start

ufw allow 'Nginx HTTP'

chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp


echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default


service nginx restart
