#!/usr/bin/env bash
# making web-server to listen on port 80 for all ipv4

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
