#!/usr/bin/env bash
# Writing script that do somethings.

echo $$ > /var/run/myscript.pid

cleanup(){
	rm -f /var/run/myscript.pid
	exit
}

trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap cleanup SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT


while true;
do
	echo "To infinity and beyond"
	sleep 2
done
