#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process



start(){
	./manage_my_process &
	pid=$(pgrep -f manage_my_process | head -1)
	echo "$pid" > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop(){
	kill -15 "$(pgrep -f manage_my_process | head -1)"
	rm -f /var/run/my_process.pid 
	echo "manage_my_process stopped"
}

restart(){
        kill -15 "$(pgrep -f manage_my_process | head -1)"
        rm -f /var/run/my_process.pid


	./manage_my_process &
        pid=$(pgrep -f manage_my_process | head -1)
        echo "$pid" > /var/run/my_process.pid
	
	echo "manage_my_process restarted"
}

if [ "$1" == "start" ];
then
	 start
elif [ "$1" == "stop" ];
then
	stop
elif [ "$1" == "restart" ];
then
	restart
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
