#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

text=$(cat /etc/passwd)
while read -r line;
do
	x=$(echo "$line" | cut -d ' ' -f 1 | cut -d ':' -f 1)
	x=$(echo "$x":"$(echo "$line" | cut -d ' ' -f 1 | cut -d ':' -f -3)")
	x=$(echo "$x":"$(echo "$line" | cut -d ' ' -f 1 | cut -d ':' -f 7)")
	echo "$x"
done <<< "$text"
