#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

text=$(cat /etc/passwd)
while IFS=: read -r user _ uid _ _ _ shell;
do
	echo "$user:$uid:$shell"
done <<< "$text"
