#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

text=$(cat /etc/passwd)

while IFS=: read -r user pass uid gid _ home shell;
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $user"
done <<< "$text"
