#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

h=0
m=1
while [ $h -lt 12 ];
do
	echo "Hour: $h"
	while [ $m -lt 60 ];
	do
		echo "$m"
		((m++))
	done
	m=0
	((h++))
done
