#!/usr/bin/env bash
# configure host file
cp /etc/hosts ~/hosts.new
sed -Ei 's/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\tlocalhost/127.0.0.2\tlocalhost/' ~/hosts.new
sed -Ei 's/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\tfacebook/8.8.8.8\tfacebook/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
